version: '3.1'

services:
  ##Db-контейнеры
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    env_file: ".env"


  ##Backend-контейнеры
  nginx:
    container_name: nginx
    build:
      context: docker/backend
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www/kusari
      - ./docker/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/backend/nginx/logs:/var/log/nginx
    ports:
      - "8091:80"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: docker/backend
      dockerfile: php-fpm.docker
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      # for macOS IP 10.254.254.254
      DOCKER_HOST: "tcp://localhost:4243"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./:/var/www/kusari
    depends_on:
      - db
    working_dir: /var/www/kusari

  ## Вспомогательные сервисы
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    env_file: ".env"
    ports:
      - "8092:80"